# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "decentral.support"
subtitle:           "Community driven support for Bitcoin"


author:
  name:             Kai Bakker
  facebook:         kaibakker
  twitter:          kaibakker
  github:           kaibakker
  linkedin:         kaibakker
  medium:           kaibakker
  # email:            your-id@your-email.com

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "kaibakker"

# URL
url:                "http://www.decentral.support"

baseurl:            ""

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# timezone:           Europ/Seoul
permalink:          /posts/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

collections:
  questions:
    output: true
    permalink: /questions/:title/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "questions"
    url:            "/questions"
  - name:           "contribute"
    url:            "/contribute"
  - name:           "about"
    url:            "/about"
  - name:           "search"
    url:            "/search"

github_repository_url: "https://github.com/kaibakker/bitcoinsupport"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path: ""
      type: my_collection
    values:
      layout: page

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - bourbon
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
